### ISSUE TITLE
[Suggestion] Add touch icons

### ISSUE THREAD

**Issue by gen-angry** [carlssonemil/damascus#1]
First off, thanks for the app. :) will be using this quite a bit during Season 4 grind.

When I add the page as a bookmark on the home page (on iphone 7), I get basically a 'black square' icon and the title text is cut off. 

It's not broken or anything, the site itself works and looks great - but adding a few meta tags would make it much cleaner for iphone bookmarks and more like an actual app. Maybe use the 'damascus camo' as an icon image?

Documentation here: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

I think Android also use the same tags for touch icons but don't have a droid device to verify.

**Comment by carlssonemil** [comment]
I added the missing favicons 👍
