### ISSUE TITLE
[Suggestion] Title bar of non-required weapons.

### ISSUE THREAD

**Issue by gen-angry** [carlssonemil/damascus#2]
On phone, I have the 'hide non required' unchecked so I can work on them all (sometimes I'll feel like using one particular weapon for a match). 

However, there's no easy way to see which weapons actually work towards Damascus without having that checked, so I'm scrolling up and down to check it on/off.

I'd like to suggest to tint the non required weapons title bar color a different shade.

**Comment by carlssonemil** [comment]
I added a small label/symbol in the corner of the required weapons.

**Comment by matt-whiteley** [comment]
Maybe change the required indicator is a small triangle in the corner of the box, rather than the dot.

When I first saw the dot I thought they meant there was a notification I should look at for those weapons.

**Comment by carlssonemil** [comment]
You're right. But I'm not sure switching to a triangle would clear that up. I will look into other possibilities.

**Comment by matt-whiteley** [comment]
A purple border along one edge?


<img width="957" alt="Screenshot 2020-06-16 at 09 37 28" src="https://user-images.githubusercontent.com/8418110/84752663-ed18fa80-afb5-11ea-82a7-171fa55e60f0.png">

**Comment by carlssonemil** [comment]
I was actually thinking of exactly that idea. If you want you can make a pull request with the changes? If not, I will add it tonight after work 😊👍
