### ISSUE TITLE
CX-9 missing mouseover text

### ISSUE THREAD

**Issue by walnuts84** [carlssonemil/damascus#36]
Here are the details: 

- Spray Paint: Kill enemies 250
- Woodland: Kill enemies with Headshots 50
- Digital: Kill enemies while Crouching 40
- Dragon: Get Hipfire Kills 30
- Splinter: Get Longshot Kills 30
- Topo: Get Double Kills 25
- Tiger: Get kills while your gun is using all attachment slots. 110
- Stripes: Get kills shortly after reloading 25
- Reptile: Get kills while your gun is using no attachment slots. 75
- Skulls: Kill 3 enemies without dying 25

**Comment by carlssonemil** [comment]
Sorry for the delay, I was gone for a few days on vacation. Should be fixed now! 😄
