### ISSUE TITLE
RAM-7 requires 150x15 kills for obsidian

### ISSUE THREAD

**Issue by florensie** [carlssonemil/damascus#4]
All assault rifles need 200x15 kills for obsidian but for some reason the RAM-7 only needs 150. This does not show in the app.
![image](https://user-images.githubusercontent.com/13403842/86177410-e4cccd80-bb26-11ea-9f56-5dc29c8f1ff5.png)

**Comment by carlssonemil** [comment]
Thanks for finding it and letting me know! 👍
