### ISSUE TITLE
Splinter Camo for 725 should be longshots not headshots

### ISSUE THREAD

**Issue by matt-whiteley** [carlssonemil/damascus#6]

**Comment by carlssonemil** [comment]
Do you want to fix this or should I, @matt-whiteley ? 😃

It's in the store/index.js and then add all individual shotguns under the splinter camo requirement. You can look at how I've done for the Topo camouflage. If not just let me know and I'll fix it!

**Comment by matt-whiteley** [comment]
Yeah, I will give it a go!
