### ISSUE TITLE
Incorrect camouflage requirements for Fennec

### ISSUE THREAD

**Issue by carlssonemil** [carlssonemil/damascus#8]
The camouflage requirement for the Fennec submachine gun are different from the rest of the sub guns.

**Requirements:**
- Spray Paint – 250 Kills
- Woodland – 50 Headshot Kills
- Digital – 40 Crouching Kills
- Dragon – 30 Hipfire Kills
- Splinter – 30 Longshot Kills
- Topo – 25 Double Kills
- Tiger – 110 Kills w/ 5 Attachments
- Stripes – 25 Kills Shortly after Reload
- Reptile – 75 Kills with 0 Attachments
- Skulls – 25 Kill 3 Enemies w/o Dying

To fix this it is needed to add all submachine gun camouflage requirements individually in [this file](https://github.com/carlssonemil/damascus/blob/master/src/store/index.js), here's an example used for the marksman rifles:
```
{
    name: 'Topo',
    requirements: {
        // ...
        'Marksman Rifle': {
            'EBR-14': '50 Longshot Kills',
            'MK2 Carbine': '50 Longshot Kills',
            'Kar98k': '50 Longshot Kills',
            'Crossbow': '50 Longshot Kills',
            'SKS': '25 Double Kills'
        },
        // ...
    }
},
```

**Comment by darman12** [comment]
I cloned your repo and added the fennec requirements to the specified file. I'm getting a 403 error when trying to push my branch. Can you advice on how to do this properly?

**Comment by carlssonemil** [comment]
You need to fork this project so that you have your own copy of it on GitHub, and then clone that forked copy. I think you're getting the 403 error because you're trying to push directly to this project, which only I am allowed to do

Here's a quick guide on what you need to do: [https://github.com/firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions)

Essentially:
1. Fork this project
2. Clone the forked project on your GitHub profile so you have it locally
3. Create a new branch for the change you're making
4. Make the necessary changes and commit them to your forked copy of this project
5. Open a pull request for me to review

Let me know if you get stuck.

This reminds me that I need to add contributing guidelines into this project.

**Comment by darman12** [comment]
Ahhh that's it, thank you. I've only contributed to other projects a couple of times so I'm not used to the process.

**Comment by carlssonemil** [comment]
I appreciate you taking the time to contribute! 😄 

I'll close this issue since commit #9 by @darman12 fixes this bug.

**Comment by darman12** [comment]
It's my pleasure :D This is the first real project I've contributed to!
